name: OSS Maven Standards Versions Update

on:
  workflow_dispatch:
  schedule:
    - cron: "25 17 * * 4"
    # at 5:25PM GMT or 3:25AM (+1) AEST on a Thursday


jobs:
  version-update:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-maven-patch-version.yml@master
    secrets: inherit
