name: Version Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "25 18 * * 1"
    # at 6:25PM GMT or 4:25AM (+1) AEST on a Monday


jobs:
  version-update:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-maven-patch-version@master
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      pull-requests: write
